[project]
name = "marimo-tutorials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kuzu>=0.11.1",
    "marimo>=0.14.17",
    "polars>=1.32.2",
    "pyarrow>=21.0.0",
]
